### ISSUE TITLE
Decoding raw codes

### ISSUE THREAD

**Issue by nitej** [robbiet480/Seville-MQTT#1]
I have been looking at the raw codes in attempt to decode them. I am finding that these are not simple nec style (although they use the same preamble,0/1 bit,postamble structure as nec) and they are much longer than 32bit (possibly 64 bit codes). Would it be possible for you to capture some of the raw ir signals for other features (like the wind mode and the sleep timer)? I only have the fan, so I cannot capture them myself. Thanks

**Comment by robbiet480** [comment]
I already did capture quite a bit of the raw data, check it out in the code [here](https://github.com/robbiet480/Seville-MQTT/blob/master/Seville-MQTT.ino#L16-L35).

As for why it looks like NEC but isn't, these issues might help you out with understanding:

https://github.com/z3t0/Arduino-IRremote/issues/356
https://github.com/markszabo/IRremoteESP8266/issues/42
https://github.com/scruss/IRTowerFanExample/issues/1

Was hoping at some point I would implement something like what AnalysIR described in the first issue I linked but the code works fine and all it would do for me is save some characters in the code along with memory.

**Comment by nitej** [comment]
I eventually decoded the entire IR command. The commands are very non-standard nec (64-bit length). The plus side is that the wind and timer commands are separate bits in the command, but there is also a parity hex digit at the end. Here is my finding https://gist.github.com/foodbag/0b4853112043b51f6de7eab139a53e16

**Comment by robbiet480** [comment]
Ah good findings @foodbag, I probably should've pointed you to the bottom of the README for my protocol notes in which I made the same findings. [Link](https://github.com/robbiet480/Seville-MQTT#protocol-notes).

Would be great for this to support timer and wind functions, although there's no use case for me personally since I use this with Home Assistant which only supports on/off, speed and oscillation.

**Comment by nitej** [comment]
Indeed, the extra wind and timer functions are probably going to be left untouched in my code base for the most part. I too only have use for on/off, speed, and oscillation (homekit). Although, one does have a use for the other functions if you are tracking the state of the fan from the leds on the fan. Luckily, if one is controlling the fan from IR, it is possible to construct a raw codes arrays directly using good approximations for the timing gaps.

**Comment by robbiet480** [comment]
Hi @foodbag, big news, I've implemented the entire IR spec in code finally, so no more hardcoded raw IR or anything. Check it out at 6490aa7b0f62aecd9ddc411ded834308f027a5f4. I've also pushed a ton more updates as well to the master branch.

Closing this as the code structure has now been entirely decoded!
